blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Community Discussion
    url: https://github.com/relaycraft/relaycraft/discussions
    about: For questions and general discussion, please use Discussions. | é—®é¢˜å’Œä¸€èˆ¬è®¨è®ºè¯·ä½¿ç”¨ Discussionsã€‚
